name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Read current version
      id: read_version
      run: |
        if [ -f VERSION ]; then
          VERSION=$(cat VERSION)
          echo "Current version: $VERSION"
        else
          VERSION="v1.0.0"
          echo "VERSION file not found, using default: $VERSION"
        fi
        # Remove 'v' prefix if present
        VERSION=${VERSION#v}
        # Increment patch version
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        PATCH=$((PATCH + 1))
        NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_VERSION"
        echo "$NEW_VERSION" > VERSION
        echo "version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Check for changes
      run: |
        if git diff --quiet && git diff --cached --quiet; then
          echo "No changes to commit."
          echo "skip_commit=true" >> $GITHUB_ENV
        else
          echo "Changes detected."
          echo "skip_commit=false" >> $GITHUB_ENV

    - name: Commit and push new version
      if: env.skip_commit == 'false'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add VERSION
        git commit -m "chore: bump version to ${{ env.version }}"
        git push

    - name: Build Docker image
      run: |
        docker build -t jasperformanceanalytics/hai:${{ env.version }} .
        docker tag jasperformanceanalytics/hai:${{ env.version }} jasperformanceanalytics/hai:latest

    - name: Push Docker image
      run: |
        docker push jasperformanceanalytics/hai:${{ env.version }}
        docker push jasperformanceanalytics/hai:latest
